In [1]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 2.1.3


In [6]:
arr1 = np.array([1,2,3,4,5])
print(f"1차원 배열: {arr1}")
arr2 = np.array([[1,2,3],[4,5,6]])
print(f"2차원 배열:\n{arr2}")

1차원 배열: [1 2 3 4 5]
2차원 배열:
[[1 2 3]
 [4 5 6]]


In [10]:
zeros = np.zeros((3,4))
ones = np.ones((2,3))
range_arr = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)
print(f"영행렬:\n{zeros}")
print(f"일행렬:\n{ones}")
print(f"범위 배열: {range_arr}")
print(f"선형 구간: {linspace}")

영행렬:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
일행렬:
[[1. 1. 1.]
 [1. 1. 1.]]
범위 배열: [0 2 4 6 8]
선형 구간: [0.   0.25 0.5  0.75 1.  ]


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"배열 모양: {arr.shape}")
print(f"배열 크기: {arr.size}")
print(f"차원 수: {arr.ndim}")
print(f"데이터 타입: {arr.dtype}")

배열 모양: (3, 3)
배열 크기: 9
차원 수: 2
데이터 타입: int64


In [12]:
reshaped = arr.reshape(1,9)
flattened = arr.flatten()
print(f"재구성된 배열: {reshaped}")
print(f"평면화된 배열: {flattened}")

재구성된 배열: [[1 2 3 4 5 6 7 8 9]]
평면화된 배열: [1 2 3 4 5 6 7 8 9]


In [14]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
print(f"덧셈: {arr1 + arr2}")
print(f"곱셈: {arr1 * arr2}")
print(f"거듭제곱: {arr1 ** 2}")

덧셈: [11 22 33 44]
곱셈: [ 10  40  90 160]
거듭제곱: [ 1  4  9 16]


In [18]:
data = np.array([82,75,98,88,77])
print(f"평균: {np.mean(data):.2f}")
print(f"표준편차: {np.std(data):.2f}")
print(f"최대값: {np.max(data)}")
print(f"최소값: {np.min(data)}")

평균: 84.00
표준편차: 8.32
최대값: 98
최소값: 75


In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"첫 번째 행: {arr[0]}")
print(f"특정 원소: {arr[1,2]}")
print(f"첫 두 행:\n{arr[:2]}")
print(f"마지막 열:\n{arr[:,-1]}")

첫 번째 행: [1 2 3]
특정 원소: 6
첫 두 행:
[[1 2 3]
 [4 5 6]]
마지막 열:
[3 6 9]


In [25]:
mask = arr > 6
print(f"6보다 큰 원소들: {arr}")

6보다 큰 원소들: [[False False False]
 [False False False]
 [ True  True  True]]
