In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print("원본 행렬 A:\n", A)


원본 행렬 A:
 [[1 2]
 [3 4]
 [5 6]]


In [2]:
A_T = A.T
print("전치된 행렬 A_T:\n", A_T)


전치된 행렬 A_T:
 [[1 3 5]
 [2 4 6]]


In [3]:
B = np.array([[1, 0],
              [0, 1]])

C = A @ B
print("A와 B의 행렬 곱 결과:\n", C)


A와 B의 행렬 곱 결과:
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
print("A.T @ A:\n", A.T @ A)
print("A @ A.T:\n", A @ A.T)


A.T @ A:
 [[35 44]
 [44 56]]
A @ A.T:
 [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
